export const EVENT_SHOW_OVERVIEW = 'EVENT_SHOW_OVERVIEW'
export const EVENT_HIDE_OVERVIEW = 'EVENT_HIDE_OVERVIEW'

export const FAILURE_SHOW_OVERVIEW = 'FAILURE_SHOW_OVERVIEW'
export const FAILURE_HIDE_OVERVIEW = 'FAILURE_HIDE_OVERVIEW'

export const EVENT_SHOW_RETRY = 'EVENT_SHOW_RETRY'
export const EVENT_HIDE_RETRY = 'EVENT_HIDE_RETRY'
export const REQUEST_EVENT_RETRY = 'REQUEST_EVENT_RETRY'
export const RECEIVE_EVENT_RETRY = 'RECEIVE_EVENT_RETRY'
export const REQUEST_EVENT_RETRY_FAILED = 'REQUEST_EVENT_RETRY_FAILED'

export const FAILURE_SHOW_RETRY = 'FAILURE_SHOW_RETRY'
export const FAILURE_HIDE_RETRY = 'FAILURE_HIDE_RETRY'
export const REQUEST_FAILURE_RETRY = 'REQUEST_FAILURE_RETRY'
export const REQUEST_FAILURE_RETRY_FAILED = 'REQUEST_FAILURE_RETRY_FAILED'
export const RECEIVE_FAILURE_RETRY = 'RECEIVE_FAILURE_RETRY'

export const FAILURE_SHOW_DELETE = 'FAILURE_SHOW_DELETE'
export const FAILURE_HIDE_DELETE = 'FAILURE_HIDE_DELETE'
export const REQUEST_FAILURE_DELETE = 'REQUEST_FAILURE_DELETE'
export const REQUEST_FAILURE_DELETE_FAILED = 'REQUEST_FAILURE_DELETE_FAILED'
export const RECEIVE_FAILURE_DELETE = 'RECEIVE_FAILURE_DELETE'

export const SEARCH_INPUT_CHANGE_FILTER_TYPE = 'SEARCH_INPUT_CHANGE_FILTER_TYPE'
export const SEARCH_INPUT_CHANGE_FILTER_VALUE = 'SEARCH_INPUT_CHANGE_FILTER_VALUE'

export const REQUEST_EVENTS_SEARCH_RESULTS = 'REQUEST_EVENTS_SEARCH_RESULTS'
export const RECEIVE_EVENTS_SEARCH_RESULTS = 'RECEIVE_EVENTS_SEARCH_RESULTS'
export const REQUEST_EVENTS_SEARCH_RESULTS_FAILED = 'REQUEST_EVENTS_SEARCH_RESULTS_FAILED'
export const LOAD_MORE_EVENTS_SEARCH_RESULTS = 'LOAD_MORE_EVENTS_SEARCH_RESULTS'
export const TRIGGER_EVENTS_SEARCH = 'TRIGGER_EVENTS_SEARCH'

export const REQUEST_FAILURES_SEARCH_RESULTS = 'REQUEST_FAILURES_SEARCH_RESULTS'
export const RECEIVE_FAILURES_SEARCH_RESULTS = 'RECEIVE_FAILURES_SEARCH_RESULTS'
export const REQUEST_FAILURES_SEARCH_RESULTS_FAILED = 'REQUEST_FAILURES_SEARCH_RESULTS_FAILED'
export const LOAD_MORE_FAILURES_SEARCH_RESULTS = 'LOAD_MORE_FAILURES_SEARCH_RESULTS'
export const TRIGGER_FAILURES_SEARCH = 'TRIGGER_FAILURES_SEARCH'

export const ADD_FLASH_MESSAGE = 'ADD_FLASH_MESSAGE'
export const DELETE_FLASH_MESSAGE = 'DELETE_FLASH_MESSAGE'

export const REQUEST_EVENT_DETAILS = 'REQUEST_EVENT_DETAILS'
export const RECEIVE_EVENT_DETAILS = 'RECEIVE_EVENT_DETAILS'
export const REQUEST_EVENT_DETAILS_FAILED = 'REQUEST_EVENT_DETAILS_FAILED'

export const REQUEST_FAILURE_DETAILS = 'REQUEST_FAILURE_DETAILS'
export const RECEIVE_FAILURE_DETAILS = 'RECEIVE_FAILURE_DETAILS'
export const REQUEST_FAILURE_DETAILS_FAILED = 'REQUEST_FAILURE_DETAILS_FAILED'

export const DELETE_FAILURE = 'DELETE_FAILURE'
