export const EVENT_SHOW_OVERVIEW = 'EVENT_SHOW_OVERVIEW'
export const EVENT_HIDE_OVERVIEW = 'EVENT_HIDE_OVERVIEW'

export const EVENT_SHOW_RETRY = 'EVENT_SHOW_RETRY'
export const EVENT_HIDE_RETRY = 'EVENT_HIDE_RETRY'
export const REQUEST_EVENT_RETRY = 'REQUEST_EVENT_RETRY'
export const RECEIVE_EVENT_RETRY = 'RECEIVE_EVENT_RETRY'
export const REQUEST_EVENT_RETRY_FAILED = 'REQUEST_EVENT_RETRY_FAILED'

export const SEARCH_INPUT_CHANGE_FILTER_TYPE = 'SEARCH_INPUT_CHANGE_FILTER_TYPE'
export const SEARCH_INPUT_CHANGE_FILTER_VALUE = 'SEARCH_INPUT_CHANGE_FILTER_VALUE'

export const REQUEST_SEARCH_RESULTS = 'REQUEST_SEARCH_RESULTS'
export const RECEIVE_SEARCH_RESULTS = 'RECEIVE_SEARCH_RESULTS'
export const REQUEST_SEARCH_RESULTS_FAILED = 'REQUEST_SEARCH_RESULTS_FAILED'
export const LOAD_MORE_SEARCH_RESULTS = 'LOAD_MORE_SEARCH_RESULTS'
export const TRIGGER_SEARCH = 'TRIGGER_SEARCH'

export const ADD_FLASH_MESSAGE = 'ADD_FLASH_MESSAGE'
export const DELETE_FLASH_MESSAGE = 'DELETE_FLASH_MESSAGE'

export const REQUEST_EVENT_DETAILS = 'REQUEST_EVENT_DETAILS'
export const RECEIVE_EVENT_DETAILS = 'RECEIVE_EVENT_DETAILS'
export const REQUEST_EVENT_DETAILS_FAILED = 'REQUEST_EVENT_DETAILS_FAILED'
